# Generated by Django 4.0 on 2023-01-01 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='watchAgain',
            new_name='watch_again',
        ),
    ]
